
TEST_LIST = \
	3Sum                                   \
	3SumClosest                            \
	4Sum                                   \
	abbreviation                           \
	abcSets                                \
	addBinary                              \
	addTwoNumbers                          \
	anagrams                               \
	balancedBinaryTree                     \
	bestTimeToBuyAndSellStock              \
	binaryTreeInOrderTraversal             \
	binaryTreeLevelTraversal               \
	binaryTreeMaxSum                       \
	binaryTreeOrderTraversal               \
	binaryTreePathSum                      \
	BinaryTreePostOrderTraversal           \
	BinaryTreePreOrderTraversal            \
	binaryTreeZigZagTraversal              \
	candy                                  \
	climbingStairs                         \
	cloneGraph                             \
	cloudera                               \
	combinations                           \
	combinationSum                         \
	constructBinaryTreeFromInPost          \
	constructBinaryTreeFromInPre           \
	containerWithMostWater                 \
	convertedSortedArrayToBinaryTree       \
	convertSortedListToBinaryTree          \
	copyListWithRandomPointer              \
	countAndSay                            \
	decodeWays                             \
	distinctSubseq                         \
	divideTwoIntegers                      \
	editDistance                           \
	fibonacci                              \
	firstMissingPositive                   \
	flattenBinaryTreeToLinkedList          \
	gasStation                             \
	generateParentheses                    \
	grayCode                               \
	insertIntervals                        \
	insertionSortList                      \
	insertSortedList                       \
	integerToRoman                         \
	interleavingString                     \
	iterator                               \
	jumpGame                               \
	kLargestElementsInArray                \
	largestRectangleInHist                 \
	lengthOfLastWord                       \
	letterCombOfPhoneNum                   \
	linkedListCycle                        \
	longestCommonPrefix                    \
	longestConsec01WithOneChange           \
	longestConsecutiveSequence             \
	longestIncreasingSequence              \
	longestPalindromicSubstr               \
	LongestPalindromicSubstring            \
	longestSubstr                          \
	longestValidParentheses                \
	lowestCommonAncester                   \
	LRUCache                               \
	maxDepthOfBinaryTree                   \
	maxDistance                            \
	maximumSubarray                        \
	maxPointsOnLine                        \
	maxRectangle                           \
	medianOfTwoSortedArr                   \
	mergeIntervals                         \
	mergeKSortedLists                      \
	mergeSortedArray                       \
	mergeTwoSortedList                     \
	minDepthOfBinaryTree                   \
	minimumPathSum                         \
	minimumWindowSubstr                    \
	minRange                               \
	multiplyString                         \
	nextPermutation                        \
	NQueens                                \
	PainterPartition                       \
	palindrome                             \
	PalindromePartitioning                 \
	PalindromePartitioningII               \
	partitionList                          \
	PascalTriangle                         \
	pathSum                                \
	permutations                           \
	permutationSequence                    \
	plusOne                                \
	populateNextRight                      \
	pow                                    \
	printLastKLinesOfFile                  \
	recoverBinarySearchTree                \
	regularExpression                      \
	regularExprMatching                    \
	removeDupFromSortedArray               \
	removeDuplicatesLinkedList             \
	removeDuplicatesSortedArr              \
	removeElement                          \
	removeNthNodeFromEndofList             \
	reorderList                            \
	restoreIPAddr                          \
	reverseInteger                         \
	reverseLinkedList                      \
	reverseNodesInKGroup                   \
	ReversePolish                          \
	reverseWordsInString                   \
	revertBits                             \
	romanToInteger                         \
	rotateImage                            \
	rotateList                             \
	sameTree                               \
	scrambleString                         \
	search2DMatrix                         \
	searchForARange                        \
	searchInRotatedSortedArr               \
	searchInsertPosition                   \
	setMatrixZeroes                        \
	simplifyPath                           \
	singleNumber                           \
	sortColors                             \
	sortList                               \
	spiralMatrix                           \
	sqrt                                   \
	stringToInteger                        \
	strStr                                 \
	subSets                                \
	subStringWithConcatOfWords             \
	sudokuSolver                           \
	sumRootToLeaf                          \
	surroundedRegions                      \
	swapNodesInPairs                       \
	symmetricTree                          \
	textJustification                      \
	trappingRainWater                      \
	Triangle                               \
	twoSigma                               \
	twoSum                                 \
	uniqBinarySearchTree                   \
	uniqPath                               \
	utf8Encoding                           \
	validateBinarySearchTree               \
	validNumber                            \
	validPalindrome                        \
	validParentheses                       \
	validSudoku                            \
	wildCardMatching                       \
	wordBreak                              \
	wordLadder                             \
	wordSearch                             \
	zigZagConversion                       \

all: ${TEST_LIST}

${TEST_LIST}::
	cd $@ && $(MAKE) && pwd && cd ..

clean:
	rm -f */a.out

